/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package azrc.az.sigtran.tcap.parameters;

/**
 * This element contains one of the problem codes which relate only to the
 * return result component type.
 *
 * @author root
 */
public enum ReturnResultProblem {
    /**
     * No operation with the specified invoke ID is in progress. This code is
     * generated by the component sublayer.
     */
    UNRECOGNIZED_INVOKE_ID(0),
    /**
     * The invoked operation does not report success. This code is generated by
     * the component sublayer.
     */
    RETURN_RESULT_UNEXPECTED(1),
    /**
     * Signifies that the type of parameter in the return result component is
     * not that agreed by the two TC-Users.
     */
    MISTYPED_PARAMETER(2);
    private int value;

    private ReturnResultProblem(int value) {
        this.value = value;
    }

    public static ReturnResultProblem getInstance(int i) {
        switch (i) {
            case 0:
                return UNRECOGNIZED_INVOKE_ID;
            case 1:
                return RETURN_RESULT_UNEXPECTED;
            case 2:
                return MISTYPED_PARAMETER;
            default:
                return null;
        }
    }

    public int value() {
        return this.value;
    }
}
